<!DOCTYPE html>
<html lang = "en">
  <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Image Upload</title>
        <link href='http://fonts.googleapis.com/css?family=Nunito:400,300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="formstyles.css">
        <script type="text/javascript" src="formscript.js"></script>
  </head>
    <body>