<!DOCTYPE html>
<html lang = "en">
  <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Moderator</title>
        <link href='http://fonts.googleapis.com/css?family=Nunito:400,300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="moderatorstyles.css">
        <script type="text/javascript" src="moderatorscript.js"></script>
        <script type="text/javascript" src="http://www.google.com/jsapi"></script>
        <script src="http://code.jquery.com/jquery.min.js"></script>
  </head>
    <body>